### ISSUE TITLE
Validation loss and Validation PSNR in progress bar not updating

### ISSUE THREAD

**Issue by adv010** [EscVM/RAMS#9]
![image](https://user-images.githubusercontent.com/40948853/125200131-d6e97680-e269-11eb-89e6-d5dd8d71259f.png)

Hey guys,

Validation loss and Validation PSNR in train_RAMS is coming consistently as 0 in the progress bar, as visible in the attached image. 

(a) Could you tell us where it might be going wrong?
(b) Does it impact the overall training process?

**Comment by EscVM** [comment]
Hi @adv010!

Sorry for the delay in the reply! 

First of all, you seriously need a GPU! You're gonna end your training in a century or so :))

Regarding the validation metrics, you're not getting any updates because you're still not validating. In line 165 of the [training](https://github.com/EscVM/RAMS/blob/master/utils/training.py) script, there's in if that triggers the validation only if you have (step % evaluate_every) == 0. So, before reaching that first step, all metrics remain at zero. Anyway, it doesn't affect the overall training process.
